### PR TITLE
[FSPE-5245] Fixed Popover arrow positioning

### PR DESCRIPTION
**Pull request by janibolkvadze**
https://ctl.atlassian.net/browse/FSPE-5245

@mattnickles @jllr

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://1b15aaac6e6b726d75120570998cdbb7057bea87-chi-pr.enterprise.ctl.io" target="_blank"> https://1b15aaac6e6b726d75120570998cdbb7057bea87-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1089/ for more details.

**Comment by mattnickles** [comment]
@jllr This method works but I've asked Jani to see if we can achieve this by making the position class dynamic instead. This will prevent a mismatch between the x-placement value and class.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://1b2b0dda01518a271d4d6ebbf5c41cf4b2a082a3-chi-pr.enterprise.ctl.io" target="_blank"> https://1b2b0dda01518a271d4d6ebbf5c41cf4b2a082a3-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1096/ for more details.

**Comment by mattnickles** [comment]
@janibolkvadze @dani-cl-madrid @jllr It doesn't look like there's going to be enough time to address this tomorrow before the release. Can we remove the change to popover.tsx and move forward with the CSS solution for now? We'll create a separate ticket for the mismatched position value and solve that issue separately.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1106/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://f55cd16df204878e1eeed5fd2dfe65c40c79f52d-chi-pr.enterprise.ctl.io" target="_blank"> https://f55cd16df204878e1eeed5fd2dfe65c40c79f52d-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1107/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-0o32f2, https://ops.elasticbox.com/services/instances/i-omuen2, https://ops.elasticbox.com/services/instances/i-3kp27w

**Comment by dani-cl-madrid** [comment]
@mattnickles @janibolkvadze I'm sorry I couldn't take a look into this yesterday. Please, let me know when the new PR is ready so I can take a look. Thank you.

**Pull request merged**
