### PR TITLE
[FSPE-6372] Added docs example for portal error modal

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-6372

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://76b3f74cfac186320fbc47f39d084c0d997c35d4-chi-pr.enterprise.ctl.io" target="_blank"> https://76b3f74cfac186320fbc47f39d084c0d997c35d4-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1357/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://a0be9ffc831222e2b8ac4f31d803814c8bc640ef-chi-pr.enterprise.ctl.io" target="_blank"> https://a0be9ffc831222e2b8ac4f31d803814c8bc640ef-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1502/ for more details.

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://a0be9ffc831222e2b8ac4f31d803814c8bc640ef-chi-pr.enterprise.ctl.io" target="_blank"> https://a0be9ffc831222e2b8ac4f31d803814c8bc640ef-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1505/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-eepa8l, https://ops.elasticbox.com/services/instances/i-au72la

**Pull request merged**
