### PR TITLE
[CHI-156] Add date picker component

### PR DESCRIPTION
**Pull request by dani-cl-madrid**
This pull request also contains Popover pull request https://github.com/CenturyLinkCloud/ux-chi/pull/193. Please review that first and then I'll rebase. 
Added datepicker component. It supports, value, max, min, format, locales.
Makes use of Day.js library (~4Kb).

### CODE REVIEW

**Comment by dani-cl-madrid** [comment]
screen_shot_2019-02-15_at_10_41_43_am
Here you can see some decisions I made related to design, maybe it should work that way, @mattnickles , please review. Thank you.

**Comment by mattnickles** [comment]
@dani-cl-madrid Looks great. The border, hover and today mark are fine. I will add a calendar icon to our library so we can swap out the pencil.

**Comment by mattnickles** [comment]
@dani-cl-madrid I've merged the popover PR so we're ready to rebase. Sending you a date picker icon now.

**Comment by mattnickles** [comment]
@dani-cl-madrid discovered a minor bug. If you click towards the bottom of an input to initiate the date picker, it renders for a brief second and disappears

**Comment by dani-cl-madrid** [comment]
@mattnickles , the minor bug you discovered must be resolved right now. I didn't receive the date picker icon.

**Comment by dani-cl-madrid** [comment]
@mattnickles One thing that is not documented as it is not decided yet is how to import additional locales. Maybe we should not waste time on this now but wanted to let you know:

Depending on how Chi JavaScript library is used, this can be accomplished in several ways:

- We can include all the locales in our package (29Kb gzipped) (easy). 
- Include only some of them (easy). 
- Provide methods to load them by the developer (we should provide 2 methods: one for being able to load the locales from a web page and another for being able to load them from a JavaScript project (es6 modules or via require or both).

**Pull request merged**
