### PR TITLE
[FSPE-6745] Added new portal icons

### PR DESCRIPTION
**Pull request by mattnickles**
* Added new portal icons
* Prepared 3.7.0 release

https://ctl.atlassian.net/browse/FSPE-6745

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://d414ff38244f865836ab6250f6b40b12e72c4340-chi-pr.enterprise.ctl.io" target="_blank"> https://d414ff38244f865836ab6250f6b40b12e72c4340-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1691/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://95b522f415197ea975fb49a2a1522761ea1353d8-chi-pr.enterprise.ctl.io" target="_blank"> https://95b522f415197ea975fb49a2a1522761ea1353d8-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1692/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-d9jtlj, https://ops.elasticbox.com/services/instances/i-g8ajpe

**Pull request merged**
