### PR TITLE
[FSPE-6598] Changed duplicate IDs and fixed odd behavior in accordion tabs

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSPE-6598

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://baa383ca6e7cb11ec0782dcd270c82a7ae7deb9e-chi-pr.enterprise.ctl.io" target="_blank"> https://baa383ca6e7cb11ec0782dcd270c82a7ae7deb9e-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1604/ for more details.

**Review by mattnickles — APPROVED** [review]

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://baa383ca6e7cb11ec0782dcd270c82a7ae7deb9e-chi-pr.enterprise.ctl.io" target="_blank"> https://baa383ca6e7cb11ec0782dcd270c82a7ae7deb9e-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1617/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-ck5uzw

**Pull request merged**
