### PR TITLE
[PE-4641] Added classname replacement guide

### PR DESCRIPTION
**Pull request by janibolkvadze**
- Added guides of automated classname replacement scripts

Thoughts about adding guides regarding removed legacy code?
Also, we need to communicate markup changes of number input component

@mattnickles @jllr

https://ctl.atlassian.net/browse/PE-4641

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://26e1f571a7c6f19fac076790c39bc9e95ba75909-chi-pr.enterprise.ctl.io" target="_blank"> https://26e1f571a7c6f19fac076790c39bc9e95ba75909-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/858/ for more details.

**Comment by jllr** [comment]
@janibolkvadze just missing to fix broken character

**Comment by mattnickles** [comment]
@janibolkvadze Yes, we'll need more guides for legacy code. Can you fix the broken characters and we'll merge this tomorrow and continue iterating on guides in a separate PR?

image
image

**Comment by janibolkvadze** [comment]
> @janibolkvadze Yes, we'll need more guides for legacy code. Can you fix the broken characters and we'll merge this tomorrow and continue iterating on guides in a separate PR?
> 
> image
> image

I simplified it a little. I think it's more clear this way. What do you think? @mattnickles @jllr

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://fef3b7d364ade74d464dd9eff4e54706efb329ac-chi-pr.enterprise.ctl.io" target="_blank"> https://fef3b7d364ade74d464dd9eff4e54706efb329ac-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/897/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-sm0t0x, https://ops.elasticbox.com/services/instances/i-k3s40k

**Pull request merged**
