### PR TITLE
[CHI-227] Install Stencil DevEnv in Chi project

### PR DESCRIPTION
**Pull request by dani-cl-madrid**
Stencil DevEnv doesn't support running in Docker yet, so a propper node environment is necessary. To run:
```
npm install
cd src/custom-elements
npm install
cd ../..
npm run start:customElements
```
This will make both DevEnvs work at the same time.
New documentation section will appear in the left menu (Custom elements)
Stencil working directory is ```src/custom-elements```
Stencil documentation in https://stenciljs.com/docs/introduction

---

Added utils file.
Added icon documentation.
Added first unitary test. Execute by running
```
cd src/custom-elements
npx stencil test --spec
```
Every comment is welcome.

### CODE REVIEW

**Comment by dani-cl-madrid** [comment]
@srinath-koneru would you be so kind to review this first Custom Elements related pull request?
It has two commits, one for the Stencil dev env, and a second for the first component (icons). You'll find further information in the pull request description. Once this is merged, it would be nice if you could make pull request for each one of your components. Documentation has the be written (it is in pug format) I'd like to add the Stencil documentation also, but I have to do some modifications on the gulp tasks and pug templates to include this information. 
Thank you in advance.

**Comment by srinath-koneru** [comment]
@dani-cl-madrid everything looks good.

**Comment by dani-cl-madrid** [comment]
@cristb, as you requested, I have changed the way type definitions are stored. Now they are located in the model's folder, and there will be one file per type. 
In the other hand, I didn't include the TS linter file we use in the new part of CAM as it doesn't
fit the project. It has Angular rules and also has angular dependencies that have nothing to do in this project. 
As an idea for the future, we might maintain our own linter files, and separate rules per technology, so we can share them between projects. I.e., one file for TypeScript that can be used in Chi Custom Elements and CAM and one for Angular that will fit CAM. 
Pleas, ack if everything is ok. Thank you!

**Comment by dani-cl-madrid** [comment]
@mattnickles , please merge this to allow us to start making pull request with custom elements. Thank you!

**Comment by davidojedacl** [comment]
@dani-cl-madrid Pending to support running in Docker yet is necessary to install both DevEnvs. i found some test error results related the test configuration json files. So is necessary to update this files. Otherwise everything ok

**Comment by dani-cl-madrid** [comment]
> @dani-cl-madrid Pending to support running in Docker yet is necessary to install both DevEnvs. i found some test error results related the test configuration json files. So is necessary to update this files. Otherwise everything ok

@davidojedacl , is this comment related to this PR or to https://github.com/CenturyLinkCloud/ux-chi/pull/264?

**Pull request merged**
