### PR TITLE
[PE-3972] Changed focus color for better consistency with brand

### PR DESCRIPTION
**Pull request by mattnickles**
- Changed input, card, and picker focus color from $secondary (Mint) to $primary (Vibrant Blue) for better consistency with brand style guides
- Fixed several sass lint warnings

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/461/ for more details.

**Comment by jllr** [comment]
@mattnickles please solve conflicts

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/479/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/481/ for more details.

**Pull request merged**
