### PR TITLE
[FSPE-6906] Improved data table sorting

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSPE-6906

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://bd43b58fede7e9f6b3ddfecd95709baf1e2656aa-chi-pr.enterprise.ctl.io" target="_blank"> https://bd43b58fede7e9f6b3ddfecd95709baf1e2656aa-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1686/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://7f03a8df35049d41f597795a0c5100c80f26e775-chi-pr.enterprise.ctl.io" target="_blank"> https://7f03a8df35049d41f597795a0c5100c80f26e775-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1693/ for more details.

**Review by janibolkvadze — APPROVED** [review]

**Review by mattnickles — COMMENTED** [review]
@jllr Looks good. One of the icons the portal team was expecting in the 3.7.0 release is icon-arrow-sort for table sorting. If we're planning to deviate from that design with icon-arrow-up, we'll need to run it by their team.

Whichever approach we move forward with, can we apply it to the table component for consistency? The data table is using arrows and the table is using chevrons.

**Comment by jllr** [comment]
@mattnickles we can discuss the deviation of the icon-arrow-sort in the UI/UX meeting on Wednesday.

It makes sense to apply those changes to the table component for consistency.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://a01a980b90a57173c02003d86c1110d7ba378b6c-chi-pr.enterprise.ctl.io" target="_blank"> https://a01a980b90a57173c02003d86c1110d7ba378b6c-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1730/ for more details.

**Review by mattnickles — APPROVED** [review]
👍

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-4wtb8l, https://ops.elasticbox.com/services/instances/i-yj7gkw, https://ops.elasticbox.com/services/instances/i-ib3ol4

**Pull request merged**
