### PR TITLE
[PE-4870] Revision for Backstop test for Picker component

### PR DESCRIPTION
**Pull request by sabah1910**
@mattnickles @janibolkvadze @jllr Revisions for https://ctl.atlassian.net/browse/FSPE-4870

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://0beab00a2b81df0fbd874f02c33c858154716bc6-chi-pr.enterprise.ctl.io" target="_blank"> https://0beab00a2b81df0fbd874f02c33c858154716bc6-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1057/ for more details.

**Comment by mattnickles** [comment]
@sabah1910 @jllr @janibolkvadze Hi Sabah, would you mind committing the fix to your previous [branch](https://github.com/sabah1910/ux-chi/tree/FIX/PE-4870-Backstop-test-for-Picker-component) instead of creating a new branch and PR?

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-4d3zg2

**Pull request closed without merging**
