### PR TITLE
[CHI-378] Adjust grid in XS and SM breakpoints to support 4 and 8 columns instead of 12

### PR DESCRIPTION
**Pull request by jllr**
@mattnickles 

https://ctl.atlassian.net/browse/CHI-387

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build STARTED. See http://jenkins.elasticbox.com/job/chi_pull_request/328/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/328/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/331/ for more details.

**Comment by mattnickles** [comment]
Thanks for putting this together. After testing it looks like this would not provide a lot of value over the current approach. Let’s stick with 12 for simplicity and we can always revisit if needed.

**Pull request closed without merging**
