### PR TITLE
[FSPE-5183] Added support for table headers with two tiers

### PR DESCRIPTION
**Pull request by mattnickles**
#### Added
* Added: Table now supports table headers with two tiers.
#### Changed
* Changed: Tables with Portal theme now render hover row behavior by default. Applying the class `-hover` is no longer necessary.
* Changed: Tables with Portal theme have been updated to reflect latest colors in portal style guide v4.
#### Fixed
* Fixed: Table header cells rendered incorrectly when placed outside of thead.
* Fixed: Tables with Inverse theme rendered incorrect border-color and border-width when class `-bordered` was applied.

#### Added
* Added: Table documentation has been updated with an example for table headers with two tiers.
* Added: Table documentation for Base state.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://f5dce0668b8d3a2abd4bef282dddebc53317bf56-chi-pr.enterprise.ctl.io" target="_blank"> https://f5dce0668b8d3a2abd4bef282dddebc53317bf56-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1061/ for more details.

**Comment by jllr** [comment]
@mattnickles just found a minor lowercase typo in Last login headers in Portal , inverse, content alignment, selectable and scrollable examples.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://705acc5e79296193cd74d0905da21167c7f1231d-chi-pr.enterprise.ctl.io" target="_blank"> https://705acc5e79296193cd74d0905da21167c7f1231d-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1066/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-duyiv6, https://ops.elasticbox.com/services/instances/i-ks1e6i

**Pull request merged**
