### PR TITLE
[PE-3924] Fixed documentation h2 heading anchors

### PR DESCRIPTION
**Pull request by janibolkvadze**
Fixed h2 anchors of documentation website

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/457/ for more details.

**Comment by grrtrr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/458/ for more details.

**Comment by jllr** [comment]
Test this please

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/464/ for more details.

**Pull request merged**
