### PR TITLE
[PE-4501] Added width sizing utility classes

### PR DESCRIPTION
**Pull request by janibolkvadze**
- [x] Added `-w--*` incremented by 5% width utility classes
- [x] Added `-w-sm--*`, `-w-md--*`, `-w-lg--*`, `-w-xl--*` incremented by 5% width utility classes
- [x] Updated sizing utility documentation page

@mattnickles @jllr 
I'm thinking about `-w--5` and `-w--10` classes.
In combination with `.a-col.-w--5`, width should be 5 columns, not 5%.
It seems to be working properly, but I'm not sure If I miss something.

https://ctl.atlassian.net/browse/PE-4501

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://be14c96ed1badf166647af7cf1212073be619494-chi-pr.enterprise.ctl.io" target="_blank"> https://be14c96ed1badf166647af7cf1212073be619494-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/735/ for more details.

**Comment by mattnickles** [comment]
@srinath-koneru

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://915b4193d92110a7bd5cda105c539155bd4e4bcc-chi-pr.enterprise.ctl.io" target="_blank"> https://915b4193d92110a7bd5cda105c539155bd4e4bcc-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/752/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-rqqmtg, https://ops.elasticbox.com/services/instances/i-t5r2et

**Pull request merged**
