### PR TITLE
[PE-4535] Fixed Price page sizes example

### PR DESCRIPTION
**Pull request by janibolkvadze**
https://ctl.atlassian.net/browse/PE-4535

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/768/ for more details.

**Comment by janibolkvadze** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://8f6829e66477f556937d502b57272d901cbaf122-chi-pr.enterprise.ctl.io" target="_blank"> https://8f6829e66477f556937d502b57272d901cbaf122-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/769/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-o2ao40

**Pull request merged**
