### PR TITLE
[FSPE-5106] Added Text Input WC skeleton screen

### PR DESCRIPTION
**Pull request by janibolkvadze**
https://ctl.atlassian.net/browse/FSPE-5106

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1039/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1040/ for more details.

**Comment by janibolkvadze** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://95ccde3c39cb43ed6b0210a278d3060ebb44fc69-chi-pr.enterprise.ctl.io" target="_blank"> https://95ccde3c39cb43ed6b0210a278d3060ebb44fc69-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1047/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://b250c580a7c7a37dc99e4825f5e1fe01c931c67c-chi-pr.enterprise.ctl.io" target="_blank"> https://b250c580a7c7a37dc99e4825f5e1fe01c931c67c-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1054/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-2goyc4, https://ops.elasticbox.com/services/instances/i-oypu8j

**Pull request merged**
