### PR TITLE
[CHI-292] Remove  margin-right in toggle switch by default

### PR DESCRIPTION
**Pull request by davidojedacl**
@mattnickles @jllr

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/43/ for more details.

**Comment by mattnickles** [comment]
@jllr

**Comment by jllr** [comment]
@davidojedacl PR is failing in Jenkins, please solve the issues and send it again

**Comment by HectorGarciaAlvarez** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/63/ for more details.

**Comment by HectorGarciaAlvarez** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/66/ for more details.

**Comment by mattnickles** [comment]
@davidojedacl can you resolve

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/109/ for more details.

**Pull request merged**
