### PR TITLE
[PE-5449] Backstop test for Alert component (Toast)

### PR DESCRIPTION
**Pull request by sabah1910**
@jllr @janibolkvadze @mattnickles https://ctl.atlassian.net/browse/FSPE-5449

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://6265192f4748641cdfffaa010a72e1997ca1586b-chi-pr.enterprise.ctl.io" target="_blank"> https://6265192f4748641cdfffaa010a72e1997ca1586b-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1187/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1193/ for more details.

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://83f43a114c6e54d85969a2b099234c6579219e78-chi-pr.enterprise.ctl.io" target="_blank"> https://83f43a114c6e54d85969a2b099234c6579219e78-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1194/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-urzed3, https://ops.elasticbox.com/services/instances/i-kaxtam

**Pull request merged**
