### PR TITLE
[PE-4799] Changed hover and active styles for base button

### PR DESCRIPTION
**Pull request by mattnickles**
- Changed hover and active styles for base button for better consistency with enterprise portal.
- Improved button tests (placed secondary buttons on black background. changed icons from inline svg to web font)
- Fixed z-index bug in datepicker documentation which caused the base example's popover to render below the disabled example.
- Updated release date for 2.0.0 in release notes.
- Fixed an example on the drawer documentation page which rendered a button incorrectly.
- Fixed a missing character on the spinner page which stated siz="" instead of size=""

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://e5571e06fefb49aad9d410fdf8967613565ea161-chi-pr.enterprise.ctl.io" target="_blank"> https://e5571e06fefb49aad9d410fdf8967613565ea161-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/933/ for more details.

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://e5571e06fefb49aad9d410fdf8967613565ea161-chi-pr.enterprise.ctl.io" target="_blank"> https://e5571e06fefb49aad9d410fdf8967613565ea161-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/934/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://1e705b9b7ec54fd6007c394f0870973957e383a1-chi-pr.enterprise.ctl.io" target="_blank"> https://1e705b9b7ec54fd6007c394f0870973957e383a1-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/935/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-13qye5, https://ops.elasticbox.com/services/instances/i-9or4kd

**Pull request merged**
