### PR TITLE
[FSPE-6979] Added support for portal pop table

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-6979

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://9bd37618a1fd75430bb80a37822d79df4db9b29a-chi-pr.enterprise.ctl.io" target="_blank"> https://9bd37618a1fd75430bb80a37822d79df4db9b29a-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1710/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://9aa2676941888ea6f56e58c90ac5e2a3ba600285-chi-pr.enterprise.ctl.io" target="_blank"> https://9aa2676941888ea6f56e58c90ac5e2a3ba600285-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1713/ for more details.

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://9aa2676941888ea6f56e58c90ac5e2a3ba600285-chi-pr.enterprise.ctl.io" target="_blank"> https://9aa2676941888ea6f56e58c90ac5e2a3ba600285-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1714/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-igdkp2, https://ops.elasticbox.com/services/instances/i-qrb7wa

**Pull request merged**
