### PR TITLE
[FSPE-5322] Improved documentation for drawer close buttons

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-5322

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1171/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1172/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://cc0f834c1e595e53f43f8ddd9c682783c144d55a-chi-pr.enterprise.ctl.io" target="_blank"> https://cc0f834c1e595e53f43f8ddd9c682783c144d55a-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1173/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-u26086, https://ops.elasticbox.com/services/instances/i-iv55uj, https://ops.elasticbox.com/services/instances/i-akevcb

**Pull request merged**
