### PR TITLE
[CHI-103] Add center alignment support to icon bubble alerts

### PR DESCRIPTION
**Pull request by davidojedacl**
@mattnickles @jllr

### CODE REVIEW

**Comment by davidojedacl** [comment]
Exist a bug in alerts component relative -bubble code example

**Comment by davidojedacl** [comment]
Maybe is necessary rename -iconCenter to -icon--center

**Comment by jllr** [comment]
@mattnickles As discussed with @davidojedacl I think alerts must be reconsidered/discussed again as they are constructed in a non scalable mode. And it makes difficult to iterate over them. We should take advantage of Icons and displays component, for example, and try to remove the :before and :after, positioning absolute... elements that they are using. Thoughts?

**Comment by mattnickles** [comment]
@jllr Agree, let's use the icon component and remove the -hasIcon class. Examples should utilize the web font - no SVGs. Also, alerts shouldn't dictate the size of the icon, we can use the icon size modifiers for that. And let's use text color utilities to color the icon to make it ultra flexible.

We'll need to change the base line-height for m-alert from 1rem to 1.25rem and then change the top and padding bottom to 0.5625rem

We can also get rid of the data title and leverage headings (e.g. a-h5) instead.

**Comment by davidojedacl** [comment]
@mattnickles you think to create a new ticket for redefine the alerts component with a new data and dimensions  or i can begin in this branch?

**Comment by mattnickles** [comment]
@davidojedacl let's use this branch

**Comment by davidojedacl** [comment]
I need this icons in webfont to make this task
screen shot 2018-11-12 at 5 55 18 pm

**Comment by mattnickles** [comment]
@davidojedacl they already exist: https://assets.ctl.io/chi/0.8.3/components/icon/
icon-circle-check
icon-circle-warning
icon-warning
icon-circle-info
icon-circle-info-outline

**Comment by davidojedacl** [comment]
ok. thanks

**Pull request closed without merging**
