### PR TITLE
[PE-3920] Fix empty form label errors in Toggle switch component

### PR DESCRIPTION
**Pull request by jllr**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/465/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/473/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/477/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/484/ for more details.

**Comment by mattnickles** [comment]
@jllr Can we close this and open a new PR based on [this branch](https://github.com/mattnickles/ux-chi/tree/PE-3920-Fix-toggle-switch-component) I sent you? The Custom Element component in this branch still needs work and ideally we would leverage what we did for the datepicker and use the `id` attribute instead of `switch-id`.

**Comment by jllr** [comment]
@mattnickles sure

**Pull request closed without merging**
