### PR TITLE
[PE-4143] Remove border-radius from all components

### PR DESCRIPTION
**Pull request by jllr**
Pending items :
- Toggle switch
- Activity

Also didn't remove the border-radius in documentation examples (example class and code and pre tags).

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/539/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/543/ for more details.

**Comment by mattnickles** [comment]
@jllr Let's keep the radius on the toggle switch component.

**Comment by mattnickles** [comment]
@jllr Edited my review comment - only one change remaining. Great work!

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/546/ for more details.

**Comment by jllr** [comment]
@mattnickles @janibolkvadze there's nothing else to address in this PR. The only reason I wrote [DON'T MERGE] is because I do not feel comfortable with this huge change in CHI and I thought it was going to be discussed in depth.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/574/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/576/ for more details.

**Pull request merged**
