### PR TITLE
[PE-4784] Added release notes for v2.0.0

### PR DESCRIPTION
**Pull request by mattnickles**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/911/ for more details.

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://5d4082a96405baeeb78b49623ca6c656f9083bf8-chi-pr.enterprise.ctl.io" target="_blank"> https://5d4082a96405baeeb78b49623ca6c656f9083bf8-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/912/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-i5rrl9

**Pull request merged**
