### PR TITLE
[PE-3918] Fixed code inconsistencies in documentation examples

### PR DESCRIPTION
**Pull request by mattnickles**
Range slider
- Stored label and input in m-form__item

Textarea
- Added missing labels and stored in m-form__item

Popover
- Added missing a-label class

Datepicker
- Added missing labels and stored in m-form__item

Drawer
- Added aria-label to hamburger menu icon button

### CODE REVIEW

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/459/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/466/ for more details.

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/467/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/468/ for more details.

**Pull request merged**
