### PR TITLE
[FSPE-6454] Added new portal icons

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-6454

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://3dfd402fbb12cfc53ec6285961936af6162b019d-chi-pr.enterprise.ctl.io" target="_blank"> https://3dfd402fbb12cfc53ec6285961936af6162b019d-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1526/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://f8aa45c909f5498759b6e7314d942601e2728355-chi-pr.enterprise.ctl.io" target="_blank"> https://f8aa45c909f5498759b6e7314d942601e2728355-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1528/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-k8ezgm, https://ops.elasticbox.com/services/instances/i-bac099

**Pull request merged**
