### PR TITLE
[PE-4034] Replace atomic class prefixes with chi

### PR DESCRIPTION
**Pull request by jllr**
- Buttons
- Icons
- Activity
- Alerts
- Avatars
- Badges
- Brand
- Breadcrumb
- Card
- Checkbox
- Datepicker
- Divider
- Drawer
- Dropdown
- Expansion panel
- Footer and header
- .a-input to .chi-input
- Modal
- Navigation and tabs
- Pagination
- Popover
- Price
- Radio
- Sidenav
- Spinner
- Steps
- Tables
- Toggle switch
- Tooltip
- Backdrop
- Grid
- Label
- Typography

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://36cf386c860358e8e33ea45d6315acd9a4c8075b-chi-pr.enterprise.ctl.io" target="_blank"> https://36cf386c860358e8e33ea45d6315acd9a4c8075b-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/702/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://afd34a8412a0b5505ef6d517f69d0845753de840-chi-pr.enterprise.ctl.io" target="_blank"> https://afd34a8412a0b5505ef6d517f69d0845753de840-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/706/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://71fc9d5ef567e245ba6da31b8525b7db5761d763-chi-pr.enterprise.ctl.io" target="_blank"> https://71fc9d5ef567e245ba6da31b8525b7db5761d763-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/707/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://2b57e8b31aac6629a83f067ab3140b7acc0f11fc-chi-pr.enterprise.ctl.io" target="_blank"> https://2b57e8b31aac6629a83f067ab3140b7acc0f11fc-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/708/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://bbddac845152e5a125817e71f117a18b70d04903-chi-pr.enterprise.ctl.io" target="_blank"> https://bbddac845152e5a125817e71f117a18b70d04903-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/710/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://5385589bc0a689f747c1564c8e257496d69caddb-chi-pr.enterprise.ctl.io" target="_blank"> https://5385589bc0a689f747c1564c8e257496d69caddb-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/712/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://20aae47514b88f92b4b1dc4b1c34b13f9f38cab9-chi-pr.enterprise.ctl.io" target="_blank"> https://20aae47514b88f92b4b1dc4b1c34b13f9f38cab9-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/713/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://e1ffea81e9eb0b969435c4bcf15ac4f49d7b3366-chi-pr.enterprise.ctl.io" target="_blank"> https://e1ffea81e9eb0b969435c4bcf15ac4f49d7b3366-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/715/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://5afe7426fdeef089c9ec9bde71540dca6c455302-chi-pr.enterprise.ctl.io" target="_blank"> https://5afe7426fdeef089c9ec9bde71540dca6c455302-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/716/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://779e8d751321e4fdf469a7b79a83b0c1b5755cdb-chi-pr.enterprise.ctl.io" target="_blank"> https://779e8d751321e4fdf469a7b79a83b0c1b5755cdb-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/718/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://f1b07309ca507e38d65031bdcda33126d3c48e09-chi-pr.enterprise.ctl.io" target="_blank"> https://f1b07309ca507e38d65031bdcda33126d3c48e09-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/719/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://7b7383235474906ff9ef6854b8b71af67121ccf4-chi-pr.enterprise.ctl.io" target="_blank"> https://7b7383235474906ff9ef6854b8b71af67121ccf4-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/720/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://5595c7d3205739e079df454fc9a710b2feb67a60-chi-pr.enterprise.ctl.io" target="_blank"> https://5595c7d3205739e079df454fc9a710b2feb67a60-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/721/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://b8aa15141bf5021ccd501784db2bfabf3bdae666-chi-pr.enterprise.ctl.io" target="_blank"> https://b8aa15141bf5021ccd501784db2bfabf3bdae666-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/723/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://9dac9ade1f8eedc454b5cf1cbb1f450bcaabf9df-chi-pr.enterprise.ctl.io" target="_blank"> https://9dac9ade1f8eedc454b5cf1cbb1f450bcaabf9df-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/724/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://7252105a9f2e8672eaec9fbc44a9bcf78ce81ee3-chi-pr.enterprise.ctl.io" target="_blank"> https://7252105a9f2e8672eaec9fbc44a9bcf78ce81ee3-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/725/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://5e130745245263183e8411db3c732fa534eef837-chi-pr.enterprise.ctl.io" target="_blank"> https://5e130745245263183e8411db3c732fa534eef837-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/726/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://db5830d4ecbc1c460a65e36611a010a6c012376d-chi-pr.enterprise.ctl.io" target="_blank"> https://db5830d4ecbc1c460a65e36611a010a6c012376d-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/728/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://3bc3c86ce328a507d3f107e9747b5027073e7ae9-chi-pr.enterprise.ctl.io" target="_blank"> https://3bc3c86ce328a507d3f107e9747b5027073e7ae9-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/729/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://3672f7dd26f48ec1dc98cedbeebf10dea40bad5c-chi-pr.enterprise.ctl.io" target="_blank"> https://3672f7dd26f48ec1dc98cedbeebf10dea40bad5c-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/731/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://7cbe766670e4e6e70bac225bf8ae473a67870956-chi-pr.enterprise.ctl.io" target="_blank"> https://7cbe766670e4e6e70bac225bf8ae473a67870956-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/732/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://d2e1a0ed12141a360571d1fd8cfe89c5f67f08a3-chi-pr.enterprise.ctl.io" target="_blank"> https://d2e1a0ed12141a360571d1fd8cfe89c5f67f08a3-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/733/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://5b6fcccdfbb55599c5309edb9e7dbeec8bd685cf-chi-pr.enterprise.ctl.io" target="_blank"> https://5b6fcccdfbb55599c5309edb9e7dbeec8bd685cf-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/734/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://e62e1bdc5edad972e6a4835362d9c3070d682256-chi-pr.enterprise.ctl.io" target="_blank"> https://e62e1bdc5edad972e6a4835362d9c3070d682256-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/736/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://fd4fb4fc779a49065bfff46a01133a047af870dc-chi-pr.enterprise.ctl.io" target="_blank"> https://fd4fb4fc779a49065bfff46a01133a047af870dc-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/737/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://4c2172767ee31bae978b45ed6df58bd91c632e1e-chi-pr.enterprise.ctl.io" target="_blank"> https://4c2172767ee31bae978b45ed6df58bd91c632e1e-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/738/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://ee6454088987968a65037176287aa799a1bf2183-chi-pr.enterprise.ctl.io" target="_blank"> https://ee6454088987968a65037176287aa799a1bf2183-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/741/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://7e7fcf5ed391b2563983d2692f622087df4f5afc-chi-pr.enterprise.ctl.io" target="_blank"> https://7e7fcf5ed391b2563983d2692f622087df4f5afc-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/742/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://76e7206f2cbc955f8e19ccc8f30337917f9f9e8c-chi-pr.enterprise.ctl.io" target="_blank"> https://76e7206f2cbc955f8e19ccc8f30337917f9f9e8c-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/743/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://71877cac453df8937b0aeba090b84cd15d2699d6-chi-pr.enterprise.ctl.io" target="_blank"> https://71877cac453df8937b0aeba090b84cd15d2699d6-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/744/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://cbd160cd7b525bca4d6986f0a325195cfb7d080c-chi-pr.enterprise.ctl.io" target="_blank"> https://cbd160cd7b525bca4d6986f0a325195cfb7d080c-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/745/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://a5d006141b6ab0fc9920a22fe9c249ded81c6dce-chi-pr.enterprise.ctl.io" target="_blank"> https://a5d006141b6ab0fc9920a22fe9c249ded81c6dce-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/750/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://604beedc9e3e8b4d00c5e33dfe0ae3611ab6dd4b-chi-pr.enterprise.ctl.io" target="_blank"> https://604beedc9e3e8b4d00c5e33dfe0ae3611ab6dd4b-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/753/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://f3fd83230b70b66d106ea483f5c7809552907580-chi-pr.enterprise.ctl.io" target="_blank"> https://f3fd83230b70b66d106ea483f5c7809552907580-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/755/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://a6d5eeab5c766e988bbe9daa337d89dc83fcccb5-chi-pr.enterprise.ctl.io" target="_blank"> https://a6d5eeab5c766e988bbe9daa337d89dc83fcccb5-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/756/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://dba769055f8d9cc4c8fe3979044b644b9fc366cb-chi-pr.enterprise.ctl.io" target="_blank"> https://dba769055f8d9cc4c8fe3979044b644b9fc366cb-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/757/ for more details.

**Comment by jllr** [comment]
@janibolkvadze good catch on the classes too. I think it works in order to have a summary of what's pending and can be done on other tickets, as we talked before. 
Remove legacy code
Refactor m-picker component
Create a consistent naming for legacy camel case CSS classes and change by de chosen one.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://732c716719087fa53d40fec906c7a55f7889ca30-chi-pr.enterprise.ctl.io" target="_blank"> https://732c716719087fa53d40fec906c7a55f7889ca30-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/758/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://fa6511e67146bcff01b95be3f62ae3fa97fe8996-chi-pr.enterprise.ctl.io" target="_blank"> https://fa6511e67146bcff01b95be3f62ae3fa97fe8996-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/760/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-ohgras, https://ops.elasticbox.com/services/instances/i-v30icr, https://ops.elasticbox.com/services/instances/i-rtiebj, https://ops.elasticbox.com/services/instances/i-nq131p, https://ops.elasticbox.com/services/instances/i-yu2ng6, https://ops.elasticbox.com/services/instances/i-9txir5, https://ops.elasticbox.com/services/instances/i-e9vg1y, https://ops.elasticbox.com/services/instances/i-svoj2c, https://ops.elasticbox.com/services/instances/i-761zxy, https://ops.elasticbox.com/services/instances/i-s7h05y, https://ops.elasticbox.com/services/instances/i-cx6r79, https://ops.elasticbox.com/services/instances/i-kn64ct, https://ops.elasticbox.com/services/instances/i-qbxfce, https://ops.elasticbox.com/services/instances/i-g8j48k, https://ops.elasticbox.com/services/instances/i-5cowbr, https://ops.elasticbox.com/services/instances/i-r9sdk0, https://ops.elasticbox.com/services/instances/i-dmxvhl, https://ops.elasticbox.com/services/instances/i-3egen8, https://ops.elasticbox.com/services/instances/i-45wtyh, https://ops.elasticbox.com/services/instances/i-8dmagc, https://ops.elasticbox.com/services/instances/i-92jvwm, https://ops.elasticbox.com/services/instances/i-bvjqf0, https://ops.elasticbox.com/services/instances/i-9usioe, https://ops.elasticbox.com/services/instances/i-dkymok, https://ops.elasticbox.com/services/instances/i-n4d8cb, https://ops.elasticbox.com/services/instances/i-t7193i, https://ops.elasticbox.com/services/instances/i-pj2xpn, https://ops.elasticbox.com/services/instances/i-ucpbml, https://ops.elasticbox.com/services/instances/i-rhada1, https://ops.elasticbox.com/services/instances/i-2vvlds, https://ops.elasticbox.com/services/instances/i-1nnzl7, https://ops.elasticbox.com/services/instances/i-p62pq6, https://ops.elasticbox.com/services/instances/i-d4yzm3, https://ops.elasticbox.com/services/instances/i-gmryk7, https://ops.elasticbox.com/services/instances/i-fzwrka, https://ops.elasticbox.com/services/instances/i-vdccav, https://ops.elasticbox.com/services/instances/i-190nxl, https://ops.elasticbox.com/services/instances/i-i6fyxw

**Pull request merged**
