### PR TITLE
[FSPE-6493] Checkbox and toggle switch improvements

### PR DESCRIPTION
**Pull request by mattnickles**
Further reduced file size of chi.css by 5kb with improvements to Checkbox and Toggle switch. This is related to FSPE-6448 but these changes required more testing.
https://ctl.atlassian.net/browse/FSPE-6493
https://ctl.atlassian.net/browse/FSPE-6448

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://bea7f57407d821329951af2550832b40635eddb7-chi-pr.enterprise.ctl.io" target="_blank"> https://bea7f57407d821329951af2550832b40635eddb7-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1544/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://e9f391667ce52c13c88e9c6aff765e46d429546c-chi-pr.enterprise.ctl.io" target="_blank"> https://e9f391667ce52c13c88e9c6aff765e46d429546c-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1552/ for more details.

**Review by janibolkvadze — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-sx667i, https://ops.elasticbox.com/services/instances/i-mozx08

**Pull request merged**
