### PR TITLE
[FSPE-5289] Added configurator to Alert component

### PR DESCRIPTION
**Pull request by janibolkvadze**
### First implementation of property configurator of Alert component

Sending this PR so that we can discuss the way we present configurators.
We are going to need some design pattern for configurators. The current design approach does not look clear enough since configurator options and the component itself do not look separated visually.
Please pay attention to the case when Alert `Title` is present and the user checks `Centered` option.

https://819d867f723fb0b3c4579fc1844ed80ecded5b64-chi-pr.enterprise.ctl.io/components/alert/

@mattnickles @jllr @gsanchezu

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://381f4c0c203d42b86539330027c14897b3dfe7c2-chi-pr.enterprise.ctl.io" target="_blank"> https://381f4c0c203d42b86539330027c14897b3dfe7c2-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1088/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://819d867f723fb0b3c4579fc1844ed80ecded5b64-chi-pr.enterprise.ctl.io" target="_blank"> https://819d867f723fb0b3c4579fc1844ed80ecded5b64-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1097/ for more details.

**Comment by gsanchezu** [comment]
Hey @janibolkvadze, looks great! But what about adding it as a new tab to the components, instead of incluing it into the `Examples` one?

**Comment by janibolkvadze** [comment]
> Hey @janibolkvadze, looks great! But what about adding it as a new tab to the components, instead of incluing it into the `Examples` one?

Thanks Guillermo! My understanding is that it is a dynamic example. I think putting it in a new tab would not be accessible enough. But I agree that in some way it must be separated from the rest of the examples. We need some design solution for this

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-3uuv89

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1323/ for more details.

**Pull request closed without merging**
