### PR TITLE
[FSPE-5179] Added support for new portal icons

### PR DESCRIPTION
**Pull request by mattnickles**
* Added: Icons `icon-attachment`, `icon-autopay`, `icon-print`, `icon-ticket-wrench`, `icon-user-outline`
* Changed: Icons `icon-address-book`, `icon-arrow-to-bottom`, `icon-user`, `icon-users`, `icon-visible-off`, `icon-visible`, `icon-x-alt` 
* Updated changelog with missing items for 2.3.0 release
* Improved Tooltip padding

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1108/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1109/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://7901154a6666f907d2bd4a1c96a636b736b07655-chi-pr.enterprise.ctl.io" target="_blank"> https://7901154a6666f907d2bd4a1c96a636b736b07655-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1110/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://857ce21ac969ae7c17eb052df8a4eb05ec752089-chi-pr.enterprise.ctl.io" target="_blank"> https://857ce21ac969ae7c17eb052df8a4eb05ec752089-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1111/ for more details.

**Comment by janibolkvadze** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://857ce21ac969ae7c17eb052df8a4eb05ec752089-chi-pr.enterprise.ctl.io" target="_blank"> https://857ce21ac969ae7c17eb052df8a4eb05ec752089-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1113/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-xosaej, https://ops.elasticbox.com/services/instances/i-nbrnow, https://ops.elasticbox.com/services/instances/i-q08hlz

**Pull request merged**
