### PR TITLE
[PE-3920] Toggle switch accessibility

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/PE-3920

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/508/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/514/ for more details.

**Comment by DiegoSanjuan** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/521/ for more details.

**Comment by mattnickles** [comment]
Closing. PR #459 is the updated version which contains the full commit history.

**Pull request closed without merging**
