### PR TITLE
[FSPE-6505] Added support of event emission to Modal JS

### PR DESCRIPTION
**Pull request by janibolkvadze**
@dani-cl-madrid @SergioQCL 

https://ctl.atlassian.net/browse/FSPE-6505

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://16913a5512bff2dfab4a6b20f4ccb5dcfa853bc7-chi-pr.enterprise.ctl.io" target="_blank"> https://16913a5512bff2dfab4a6b20f4ccb5dcfa853bc7-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1547/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://67985760403ee27a51b1230ae8ac4a7d00e07bd1-chi-pr.enterprise.ctl.io" target="_blank"> https://67985760403ee27a51b1230ae8ac4a7d00e07bd1-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1558/ for more details.

**Review by SergioQCL — APPROVED** [review]
Just some minor tweaks

**Review by dani-cl-madrid — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://1cf054245a6b1b08325487a4a31b8aa05ae61ae9-chi-pr.enterprise.ctl.io" target="_blank"> https://1cf054245a6b1b08325487a4a31b8aa05ae61ae9-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1562/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-y2nnu9, https://ops.elasticbox.com/services/instances/i-0436r6, https://ops.elasticbox.com/services/instances/i-ckoycv

**Pull request merged**
