### PR TITLE
[FSPE-5230] Add search bar component

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSPE-5230

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://1c20a361934736f7f01070c1bbfe38176119ba71-chi-pr.enterprise.ctl.io" target="_blank"> https://1c20a361934736f7f01070c1bbfe38176119ba71-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1322/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://5cc216e04da8217da4a34f685881528362eceafe-chi-pr.enterprise.ctl.io" target="_blank"> https://5cc216e04da8217da4a34f685881528362eceafe-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1334/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://b4531bd7d1befead5b47ef18a867871f0ed4beb1-chi-pr.enterprise.ctl.io" target="_blank"> https://b4531bd7d1befead5b47ef18a867871f0ed4beb1-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1350/ for more details.

**Comment by davisein** [comment]
jenkins, test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1659/ for more details.

**Comment by DiegoSanjuan** [comment]
Jenkins, test this please.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://483cd1db9515d997c5e2966191ce5c98c2c7e894-chi-pr.enterprise.ctl.io" target="_blank"> https://483cd1db9515d997c5e2966191ce5c98c2c7e894-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1766/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://14b069495e01e6d742301e4f821b71ce9aa51539-chi-pr.enterprise.ctl.io" target="_blank"> https://14b069495e01e6d742301e4f821b71ce9aa51539-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1773/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://a8d4a704ef2c3c11ec2af295a83223ebc612c7e3-chi-pr.enterprise.ctl.io" target="_blank"> https://a8d4a704ef2c3c11ec2af295a83223ebc612c7e3-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1775/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://462e0904e5d2320ddd925dee83887a3aee2f7bae-chi-pr.enterprise.ctl.io" target="_blank"> https://462e0904e5d2320ddd925dee83887a3aee2f7bae-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1784/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://b0dbe1ea20d4e3611be5f1e58426d6467ec8f670-chi-pr.enterprise.ctl.io" target="_blank"> https://b0dbe1ea20d4e3611be5f1e58426d6467ec8f670-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1813/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1815/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-fgmkmb, https://ops.elasticbox.com/services/instances/i-n945ye, https://ops.elasticbox.com/services/instances/i-6zgpph, https://ops.elasticbox.com/services/instances/i-xx972d, https://ops.elasticbox.com/services/instances/i-h6fm8p, https://ops.elasticbox.com/services/instances/i-xd04qs, https://ops.elasticbox.com/services/instances/i-e8vnuh, https://ops.elasticbox.com/services/instances/i-emt4sf

**Pull request closed without merging**
