### PR TITLE
[FSPE-6388] Improved text input and textarea documentation examples

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-6388

#### Added
* Added: Form inputs now support Help icon buttons to display helpful information about an input in a popover.
* Added: Checkbox now supports a danger state for providing error feedback to users when validation fails.
* Added: Text input and Textarea now support the readonly attribute to prevent users from changing their value.
* Added: Textarea now supports the placeholder attribute to provide users with an example of the type of data that can be entered into an input.
#### Changed
* Changed: Checkbox display from block to flex to support required and help states.
* Changed: Form items with -row layout now apply a padding-right to child input labels to eliminate need for a spacing utility class.
* Changed: Form items with label wrapper now style icons using a child combinator instead of a descendant combinator to support help icon buttons.
#### Fixed
* Fixed: Label required asterisk color no longer fails color contrast test.
* Fixed: Textarea web component specific styles were not loading due to an incorrect :host() psuedo-class.
#### Added
* Added: Checkbox documentation examples for: Checked, Required, Help, Message, Error, and Grid.
* Added: Text input documentation examples for: Readonly, Placeholder, Required, Optional, Help, Message, and Error.
* Added: Textarea documentation examples for: Readonly, Placeholder, Required, Optional, Help, Message, and Error.
* Added: Textarea documentation examples for Layout Variations.
#### Changed
* Changed: Checkbox documentation code samples have been improved.
* Changed: Text Input documentation code samples have been improved.
* Changed: Textarea documentation code samples have been improved.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://0b6fa463e503ac411c385411f49eda2437f436a5-chi-pr.enterprise.ctl.io" target="_blank"> https://0b6fa463e503ac411c385411f49eda2437f436a5-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1496/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by jllr** [comment]
@mattnickles great addition to Chi's documentation

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-gepewl

**Pull request merged**
