### PR TITLE
[FSPE-6757] Added Disabled button Tooltip example

### PR DESCRIPTION
**Pull request by janibolkvadze**
https://ctl.atlassian.net/browse/FSPE-6757

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1700/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://e08536e2be5c34b33afc8f6f49ecff6e7d08b72a-chi-pr.enterprise.ctl.io" target="_blank"> https://e08536e2be5c34b33afc8f6f49ecff6e7d08b72a-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1701/ for more details.

**Review by jllr — APPROVED** [review]

**Review by mattnickles — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-etg1bd

**Pull request merged**
