### PR TITLE
[PE-4533] Fixed floating label text input

### PR DESCRIPTION
**Pull request by janibolkvadze**
@dani-cl-madrid @mattnickles @jllr 

https://ctl.atlassian.net/browse/PE-4533

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://c5da00bfb8abd387239a9370a851d23544bd820a-chi-pr.enterprise.ctl.io" target="_blank"> https://c5da00bfb8abd387239a9370a851d23544bd820a-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/774/ for more details.

**Comment by jllr** [comment]
@janibolkvadze when input is not focused, the placeholder gets back to its original position and overlap the data that has been entered

Screen Shot 2020-03-17 at 4 43 22 PM

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-i62ny9

**Pull request closed without merging**
