### PR TITLE
[FSPE-7218] Added support of chi publish-chi-vue

### PR DESCRIPTION
**Pull request by janibolkvadze**
https://ctl.atlassian.net/browse/FSPE-7218

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://2a650901b6375f36c3b3177511658c0328db314d-chi-pr.enterprise.ctl.io" target="_blank"> https://2a650901b6375f36c3b3177511658c0328db314d-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1755/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://87a10981949359339570ee59e7416e5a9721b8c6-chi-pr.enterprise.ctl.io" target="_blank"> https://87a10981949359339570ee59e7416e5a9721b8c6-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1758/ for more details.

**Review by jfranciscohernbal — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1761/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://0ea7aa39973f581a8e290a45c68d639f88a332dd-chi-pr.enterprise.ctl.io" target="_blank"> https://0ea7aa39973f581a8e290a45c68d639f88a332dd-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1762/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-lwey3w, https://ops.elasticbox.com/services/instances/i-6u3cip, https://ops.elasticbox.com/services/instances/i-cgcgrm

**Pull request merged**
