### PR TITLE
[FSPE-6656] Added support for compact portal stat design

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-6656

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://31727f85418f758c4796ff6b8333c2752ca87ea5-chi-pr.enterprise.ctl.io" target="_blank"> https://31727f85418f758c4796ff6b8333c2752ca87ea5-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1637/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://920215c37ebef5c2d67562d1e1adfd80f81ccfe4-chi-pr.enterprise.ctl.io" target="_blank"> https://920215c37ebef5c2d67562d1e1adfd80f81ccfe4-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1639/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-45ev46, https://ops.elasticbox.com/services/instances/i-l3ihmn

**Pull request merged**
