### PR TITLE
Fix item 3 text that was not the same and not even truncated

### PR DESCRIPTION
**Pull request by gsanchezu**
@jllr, @mattnickles, 👍?

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://b974cbf349718e265d7e7f9a84c2af31504039be-chi-pr.enterprise.ctl.io" target="_blank"> https://b974cbf349718e265d7e7f9a84c2af31504039be-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1119/ for more details.

**Comment by mattnickles** [comment]
@gsanchezu good catch 👍

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-za0hiy

**Pull request merged**
