### PR TITLE
[FSPE-6064] chi range slider test cases

### PR DESCRIPTION
**Pull request by joshua22-11**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://64578a6c4cf1f62295bc5b9990e9bddd97011882-chi-pr.enterprise.ctl.io" target="_blank"> https://64578a6c4cf1f62295bc5b9990e9bddd97011882-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1576/ for more details.

**Review by janibolkvadze — CHANGES_REQUESTED** [review]
The test cases check the quality of test HTML markup itself.
They will give false positives and consume time.
I believe the difficulty is invoking Drag and Drop interaction. What is the status of using Cypress Drag Drop plugin? https://github.com/4teamwork/cypress-drag-drop

**Comment by jllr** [comment]
@joshua22-11 any advance on Jani's questions regarding test cases and Cypress drag and drop plugin? Thanks in advance

**Comment by joshua22-11** [comment]
> The test cases check the quality of test HTML markup itself.
> They will give false positives and consume time.
> I believe the difficulty is invoking Drag and Drop interaction. What is the status of using Cypress Drag Drop plugin? https://github.com/4teamwork/cypress-drag-drop

Hi @janibolkvadze , the cypress drag drop plugin was implemented but it is a roadblock since the .drag and .move functionality is not working as expected, though the chi-input thumb shifts position in the range slider, unable to get the current value of the chi-input thumb.

**Comment by gsanchezu** [comment]
Hey @janibolkvadze, @joshua22-11 , how is this going?

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://a11e82be2fe141b8dd12dc092a49b3e2aaf8650e-chi-pr.enterprise.ctl.io" target="_blank"> https://a11e82be2fe141b8dd12dc092a49b3e2aaf8650e-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1636/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://13f6a9a7202b5dce234dce90d1e3a36405f75f87-chi-pr.enterprise.ctl.io" target="_blank"> https://13f6a9a7202b5dce234dce90d1e3a36405f75f87-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1638/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://73d2b90ca23e0bff788b929551ab6f8bdfed4a51-chi-pr.enterprise.ctl.io" target="_blank"> https://73d2b90ca23e0bff788b929551ab6f8bdfed4a51-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1642/ for more details.

**Comment by janibolkvadze** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://73d2b90ca23e0bff788b929551ab6f8bdfed4a51-chi-pr.enterprise.ctl.io" target="_blank"> https://73d2b90ca23e0bff788b929551ab6f8bdfed4a51-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1643/ for more details.

**Comment by janibolkvadze** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://73d2b90ca23e0bff788b929551ab6f8bdfed4a51-chi-pr.enterprise.ctl.io" target="_blank"> https://73d2b90ca23e0bff788b929551ab6f8bdfed4a51-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1644/ for more details.

**Review by janibolkvadze — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-jy420s, https://ops.elasticbox.com/services/instances/i-dg5tr4, https://ops.elasticbox.com/services/instances/i-9x865t, https://ops.elasticbox.com/services/instances/i-166icg

**Pull request merged**
