### PR TITLE
[FSPE-5964] Added support of ES6 boilerplate

### PR DESCRIPTION
**Pull request by janibolkvadze**
@dani-cl-madrid @SergioQCL 

https://ctl.atlassian.net/browse/FSPE-5964

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://23f2c37db98ba7b03a288e2e3ac4967ae441c392-chi-pr.enterprise.ctl.io" target="_blank"> https://23f2c37db98ba7b03a288e2e3ac4967ae441c392-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1572/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://266d2b99c9b3193c3179754156236151bbc3dd08-chi-pr.enterprise.ctl.io" target="_blank"> https://266d2b99c9b3193c3179754156236151bbc3dd08-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1573/ for more details.

**Comment by janibolkvadze** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://266d2b99c9b3193c3179754156236151bbc3dd08-chi-pr.enterprise.ctl.io" target="_blank"> https://266d2b99c9b3193c3179754156236151bbc3dd08-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1574/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://06d08de37990c6ba4a5924d10f0a29d877ba8a1c-chi-pr.enterprise.ctl.io" target="_blank"> https://06d08de37990c6ba4a5924d10f0a29d877ba8a1c-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1589/ for more details.

**Review by SergioQCL — APPROVED** [review]
LGTM

**Review by dani-cl-madrid — APPROVED** [review]
LGTM

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://63e47856bf898452da7b3cc786b6c7275915e744-chi-pr.enterprise.ctl.io" target="_blank"> https://63e47856bf898452da7b3cc786b6c7275915e744-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1603/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://6a16dcdeafd9317d78eca31e6debf4464cd11dff-chi-pr.enterprise.ctl.io" target="_blank"> https://6a16dcdeafd9317d78eca31e6debf4464cd11dff-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1610/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-vjclnr, https://ops.elasticbox.com/services/instances/i-lubfd4, https://ops.elasticbox.com/services/instances/i-jdbel7, https://ops.elasticbox.com/services/instances/i-c4y21n, https://ops.elasticbox.com/services/instances/i-1j2nos

**Pull request merged**
