### PR TITLE
[Test] Test providing type attribute to Pagination WC Buttons

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://a6d71076813f5f0b9edc9127a6825540979b556a-chi-pr.enterprise.ctl.io" target="_blank"> https://a6d71076813f5f0b9edc9127a6825540979b556a-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1738/ for more details.

**Review by mattnickles — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1739/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-x086we

**Pull request closed without merging**
