### PR TITLE
[FSPE-7310] Prepared 3.9.0 release

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-7310

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1770/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://47bae497004a273a339b8d6e9f3deada2c355dbf-chi-pr.enterprise.ctl.io" target="_blank"> https://47bae497004a273a339b8d6e9f3deada2c355dbf-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1771/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-fny951

**Pull request merged**
