### PR TITLE
[FSPE-5483] Removed transparent border from alert

### PR DESCRIPTION
**Pull request by mattnickles**
* Removed transparent top border from banner alerts to make it easier to achieve portal-styled alerts with border utilities.
* Increased banner alert top and bottom padding to make up for the 2px height loss due to removing borders.
* Removed references to banner-border-color as it is no longer needed.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1170/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://087680139e97ee84ceadef4384c3dc1c1f7aaa27-chi-pr.enterprise.ctl.io" target="_blank"> https://087680139e97ee84ceadef4384c3dc1c1f7aaa27-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1174/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-1vcs4u, https://ops.elasticbox.com/services/instances/i-2ydsip

**Pull request merged**
