### PR TITLE
[PE-4209] Added copyright text to compiled chi.js

### PR DESCRIPTION
**Pull request by janibolkvadze**
Configured Gulp `build:chi:scripts` task to support adding copyright text on top.
The text must be changed to the real copyright text, but the implementation works fine when `chi build` command is launched.
Screenshot 2020-02-06 at 14 55 48
Thoughts about addings copyright text to compiled **chi.css**, **chi-icons.js** and **chi-ce.js** as well? @mattnickles @jllr @dani-cl-madrid 

https://ctl.atlassian.net/browse/PE-4209

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/603/ for more details.

**Comment by jllr** [comment]
Looks good to me. Only pending def copyright text. I would add to the other files. Good catch @janibolkvadze. @mattnickles @dani-cl-madrid thoughts?

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/608/ for more details.

**Comment by janibolkvadze** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/610/ for more details.

**Pull request merged**
