### PR TITLE
[PE-4906] Changed base font from Open Sans to Inter

### PR DESCRIPTION
**Pull request by mattnickles**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/960/ for more details.

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/961/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/962/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/963/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/964/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://63b7cb28cd8a490d12b31613e88f09ea5d51ef9b-chi-pr.enterprise.ctl.io" target="_blank"> https://63b7cb28cd8a490d12b31613e88f09ea5d51ef9b-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/965/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://15b5d61f4eea6f43a00e208f1f5f86f103c849da-chi-pr.enterprise.ctl.io" target="_blank"> https://15b5d61f4eea6f43a00e208f1f5f86f103c849da-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/970/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://0079f4c8dd4521489284cadcc8a6eec894c36093-chi-pr.enterprise.ctl.io" target="_blank"> https://0079f4c8dd4521489284cadcc8a6eec894c36093-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/972/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/973/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://90a754fbb70e367e76a4d426bd94dabfdfa3b392-chi-pr.enterprise.ctl.io" target="_blank"> https://90a754fbb70e367e76a4d426bd94dabfdfa3b392-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/974/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-vsbrss, https://ops.elasticbox.com/services/instances/i-xd8onz, https://ops.elasticbox.com/services/instances/i-fz7arc, https://ops.elasticbox.com/services/instances/i-z7ai9z

**Pull request merged**
