### PR TITLE
[FSPE-5109]-Sub Resource Integrity -hash code generating for chi.css and chi.js files

### PR DESCRIPTION
**Pull request by hanyjohny**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1744/ for more details.

**Comment by hanyjohny** [comment]
@janibolkvadze  could you please review this PR

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1745/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1746/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://437f78ada04b038c3bd6be614c933d09d768362c-chi-pr.enterprise.ctl.io" target="_blank"> https://437f78ada04b038c3bd6be614c933d09d768362c-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1747/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://8a77780c5f6b5ac6ae7d4f0c89e4a7ca9df11027-chi-pr.enterprise.ctl.io" target="_blank"> https://8a77780c5f6b5ac6ae7d4f0c89e4a7ca9df11027-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1795/ for more details.

**Review by mattnickles — COMMENTED** [review]
Looks like the crossorigin attribute must be present to check the integrity of the file:

- https://www.w3.org/TR/SRI/#cross-origin-data-leakage
- https://www.npmjs.com/package/ember-cli-sri#crossorigin-attribute
- https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#cross-origin_resource_sharing_and_subresource_integrity

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://f40dc6da2bb084cc8d1795bf2ca8647df55661f0-chi-pr.enterprise.ctl.io" target="_blank"> https://f40dc6da2bb084cc8d1795bf2ca8647df55661f0-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1802/ for more details.

**Review by jllr — APPROVED** [review]

**Review by mattnickles — COMMENTED** [review]
@janibolkvadze how would you like to handle adding the integrity on the CSS and JS files in the angular, es6, react, stencil, and vue boilerplates? can we automate this as well?

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-bb3bl5, https://ops.elasticbox.com/services/instances/i-i0401k, https://ops.elasticbox.com/services/instances/i-f7yc8a

**Pull request closed without merging**
