### PR TITLE
[CHI-315] Dropdown triggers are rendering incorrect color

### PR DESCRIPTION
**Pull request by mattnickles**
Dropdown triggers were previously constructed with an SVG background image. This led to a bug where in all buttons except for the base style, the SVG color didn't match the dropdown text color. This change converts the trigger to a webfont icon which inherits the dropdown text color.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/167/ for more details.

**Comment by dani-cl-madrid** [comment]
Test this please

**Comment by dani-cl-madrid** [comment]
Test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/171/ for more details.

**Comment by dani-cl-madrid** [comment]
Test this please

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/172/ for more details.

**Pull request merged**
