### PR TITLE
[FSPE-4807] Fixed Progress Web Component IE11 rendering issue

### PR DESCRIPTION
**Pull request by janibolkvadze**
- [x] Fixed IE11 rendering issue
- [x] Updated documentation examples and code snippets

@mattnickles @jllr 

https://ctl.atlassian.net/browse/FSPE-4807

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://95ca93f12a69aed7822c302796caa28669590ebd-chi-pr.enterprise.ctl.io" target="_blank"> https://95ca93f12a69aed7822c302796caa28669590ebd-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1509/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://3787a3008ea20f354e2ec09ee62f4b741ddb424c-chi-pr.enterprise.ctl.io" target="_blank"> https://3787a3008ea20f354e2ec09ee62f4b741ddb424c-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1510/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://ef4e683d1484a7725403dd4150a188ecf7a8fac9-chi-pr.enterprise.ctl.io" target="_blank"> https://ef4e683d1484a7725403dd4150a188ecf7a8fac9-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1511/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1512/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://ecb600502c8db2fb75f7e49aef78329e7af68a70-chi-pr.enterprise.ctl.io" target="_blank"> https://ecb600502c8db2fb75f7e49aef78329e7af68a70-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1513/ for more details.

**Review by mattnickles — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://da7f4bb1efb64d715fb2a559693f0c91e304a0d0-chi-pr.enterprise.ctl.io" target="_blank"> https://da7f4bb1efb64d715fb2a559693f0c91e304a0d0-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1524/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-z720ry, https://ops.elasticbox.com/services/instances/i-ntieid, https://ops.elasticbox.com/services/instances/i-jnklnc, https://ops.elasticbox.com/services/instances/i-kmzjco, https://ops.elasticbox.com/services/instances/i-7jo5id

**Pull request merged**
