### PR TITLE
[CHI-396] Fixed tabs component dropdown position in -lg

### PR DESCRIPTION
**Pull request by janibolkvadze**
- Fixed tabs component dropdown arrow position for -lg tabs
- Fixed toggle switch CE view issue

@jllr

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/373/ for more details.

**Comment by janibolkvadze** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/374/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/377/ for more details.

**Comment by jllr** [comment]
@janibolkvadze tests are failing in jenkins, please solve them

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/385/ for more details.

**Pull request merged**
