### PR TITLE
[FSPE-6973] Added support of language change to Date wc

### PR DESCRIPTION
**Pull request by janibolkvadze**
@SergioQCL 

https://ctl.atlassian.net/browse/FSPE-6973

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://346c0159202644b66f14b81b02ece13f6fccb096-chi-pr.enterprise.ctl.io" target="_blank"> https://346c0159202644b66f14b81b02ece13f6fccb096-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1705/ for more details.

**Review by SergioQCL — APPROVED** [review]
ACK

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-wlcnfj

**Pull request merged**
