### PR TITLE
[FSPE-6024] Fixed Popover WC shown/hidden event emission

### PR DESCRIPTION
**Pull request by janibolkvadze**
@dani-cl-madrid @SergioQCL 

https://ctl.atlassian.net/browse/FSPE-6024

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://8b6c6c6884bfa9f8812970bba14a2ecc0e617028-chi-pr.enterprise.ctl.io" target="_blank"> https://8b6c6c6884bfa9f8812970bba14a2ecc0e617028-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1292/ for more details.

**Review by mattnickles — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-g8tbu7

**Review by dani-cl-madrid — COMMENTED** [review]
That's it. Perfect. Thank you!

**Pull request merged**
