### PR TITLE
[FSPE-7379] Changed Popover component positioning

### PR DESCRIPTION
**Pull request by janibolkvadze**
Helpful information goes here.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://6a45ebd60688052a1c7f4ca67c5f2f99c9cd5307-chi-pr.enterprise.ctl.io" target="_blank"> https://6a45ebd60688052a1c7f4ca67c5f2f99c9cd5307-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1791/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://d2cae15e07ccc892463978f1fdba2208a1e20ca1-chi-pr.enterprise.ctl.io" target="_blank"> https://d2cae15e07ccc892463978f1fdba2208a1e20ca1-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1792/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-nruytt, https://ops.elasticbox.com/services/instances/i-ugoltr

**Pull request merged**
