### PR TITLE
[CHI-295] CE - Tabs (Static)

### PR DESCRIPTION
**Pull request by SergioQCL**
First version of Tabs component with no animation neither responsiveness.

@dani-cl-madrid @srinath-koneru @jllr  please take a look

Important: should be merged after Updated stencil PR: https://github.com/CenturyLinkCloud/ux-chi/pull/351

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/188/ for more details.

**Comment by SergioQCL** [comment]
test this please

**Comment by SergioQCL** [comment]
test this please

**Comment by SergioQCL** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/189/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/191/ for more details.

**Comment by SergioQCL** [comment]
test this please

**Comment by srinath-koneru** [comment]
test this please

**Comment by srinath-koneru** [comment]
> First version of Tabs component with no animation neither responsiveness.
> 
> @dani-cl-madrid @srinath-koneru @JLL please take a look

@SergioQCL who is JLL ?

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/197/ for more details.

**Comment by SergioQCL** [comment]
@srinath-koneru sorry, I meant Jose Luis. I'm editing it.. thanks for the catch!

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/200/ for more details.

**Comment by SergioQCL** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/201/ for more details.

**Comment by SergioQCL** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/202/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/203/ for more details.

**Comment by SergioQCL** [comment]
@mattnickles @jllr I'm closing it again since I can't actually dedicate time to solve the bunch of conflicts that have appeared. I'll get back to this as soon as possible.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/394/ for more details.

**Pull request closed without merging**
