### PR TITLE
Fixed Sidenav Chevron icon positioning in IE11

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1168/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://d970b387ab692c6e83de89deca4c48800b813f4b-chi-pr.enterprise.ctl.io" target="_blank"> https://d970b387ab692c6e83de89deca4c48800b813f4b-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1169/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-r73rvp

**Pull request merged**
