### PR TITLE
[PE-5447] Backstop test for Alert component (Bubble)

### PR DESCRIPTION
**Pull request by sabah1910**
@jllr @janibolkvadze @mattnickles https://ctl.atlassian.net/browse/FSPE-5447

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://7e23185701ec4091030e857375d74828be718b86-chi-pr.enterprise.ctl.io" target="_blank"> https://7e23185701ec4091030e857375d74828be718b86-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1183/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1195/ for more details.

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://f7584bce014349516ce4adb511d4818a1257d26f-chi-pr.enterprise.ctl.io" target="_blank"> https://f7584bce014349516ce4adb511d4818a1257d26f-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1196/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-yxl11n, https://ops.elasticbox.com/services/instances/i-p4f0hn

**Pull request merged**
