### PR TITLE
[PE-4031] Fix sass lint errors

### PR DESCRIPTION
**Pull request by janibolkvadze**
Fixed these SASS lint errors and warnings:

- [x] Commas should be followed by a space
- [x] Variable naming errors
- [x] Selectors must be placed on new lines
- [x] Space expected between blocks
- [x] Attribute-selector should be nested within its parent Type-selector
- [x] Type-selector should be nested within its parent Class
- [x] Type-selector should be nested within its parent Type-selector
- [x] Mixins should come before declarations
- [x] Qualifying elements are not allowed for class selectors
- [x] Indentation
- [x] Whitespace required before {
- [x] Function name should be written in lowercase with hyphens
- [x] Parenthesis should be removed
- [x] No trailing whitespace allowed

---
In case of these errors I think we should consider changing SASS conventions:
- [ ] Vendor prefixes should not be used // Used in several components for IE hacks, webfont icons, etc.
- [ ] * (universal) selectors are not allowed // Used in sidenav, picker, expansion-panel
- [ ] Values for property '***' may not use em, vh units

---
I also left several errors of picker component, because fixing them would require big refactoring and I think we should do it when the legacy code is removed.

@mattnickles @jllr 

https://ctl.atlassian.net/browse/PE-4031

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/499/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/503/ for more details.

**Comment by jllr** [comment]
@janibolkvadze can you solve the conflict please?

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/504/ for more details.

**Comment by janibolkvadze** [comment]
> @janibolkvadze This is a huge improvement. Nice work! We'll need vendor prefixes for scenarios like those you mentioned. The use of em units in the range slider component does not appear to be critical and can be changed. Open to changing lint rules for universal selectors. We can sync tomorrow and discuss further but this looks great.

Great, thanks!

**Pull request merged**
