### PR TITLE
[FSPE-6713] Changed alignment of portal Stat info icon

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-6713

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://6602da352de3212931c9e1bafcaf6e2ba4b2cc1e-chi-pr.enterprise.ctl.io" target="_blank"> https://6602da352de3212931c9e1bafcaf6e2ba4b2cc1e-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1667/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://8dc7605b22531ad36775eeb30c7a170630294f8c-chi-pr.enterprise.ctl.io" target="_blank"> https://8dc7605b22531ad36775eeb30c7a170630294f8c-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1670/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-cgslde, https://ops.elasticbox.com/services/instances/i-pehre3

**Pull request merged**
