### PR TITLE
FSPE-5297 Implemented focusVisibility function in chi.js

### PR DESCRIPTION
**Pull request by janibolkvadze**
@dani-cl-madrid @SergioQCL 

https://ctl.atlassian.net/browse/FSPE-5297

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://4d44b6f8df9bfcea5f2ed4b9db66a64e13b17268-chi-pr.enterprise.ctl.io" target="_blank"> https://4d44b6f8df9bfcea5f2ed4b9db66a64e13b17268-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1545/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://42f93000306ca8e5e7bd58c385c4ed6c2e195e1b-chi-pr.enterprise.ctl.io" target="_blank"> https://42f93000306ca8e5e7bd58c385c4ed6c2e195e1b-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1570/ for more details.

**Review by SergioQCL — APPROVED** [review]
LGTM

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://3a7f10fd14aa54a5fbf165073e444f6d8de6a6f7-chi-pr.enterprise.ctl.io" target="_blank"> https://3a7f10fd14aa54a5fbf165073e444f6d8de6a6f7-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1577/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://cf6fb3cdf552c3170106f92514bfda04916ccd63-chi-pr.enterprise.ctl.io" target="_blank"> https://cf6fb3cdf552c3170106f92514bfda04916ccd63-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1579/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-wxobkr, https://ops.elasticbox.com/services/instances/i-ba1u54, https://ops.elasticbox.com/services/instances/i-k6bs0v, https://ops.elasticbox.com/services/instances/i-2kpefu

**Pull request closed without merging**
