### PR TITLE
[FSPE-6478] Badge improvements

### PR DESCRIPTION
**Pull request by mattnickles**
Removed fixed height from badges to enable support for text size utility classes (e.g. -text--lg, -text--xl). Not needed for 3.3.0 release.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://871790f922d88f5dbfc5de251cb831c534fece95-chi-pr.enterprise.ctl.io" target="_blank"> https://871790f922d88f5dbfc5de251cb831c534fece95-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1530/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://ec80b2f54e8a14d408829987050568d14ad4f4d3-chi-pr.enterprise.ctl.io" target="_blank"> https://ec80b2f54e8a14d408829987050568d14ad4f4d3-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1538/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-cogd3i, https://ops.elasticbox.com/services/instances/i-rf5v2d

**Pull request merged**
