### PR TITLE
[FSPE-6377] Prepared Chi 3.2.0 release

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-6377

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1402/ for more details.

**Comment by janibolkvadze** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://b67c5ef7f9cc9a3a7464e7c51dd63b1a0034b4c3-chi-pr.enterprise.ctl.io" target="_blank"> https://b67c5ef7f9cc9a3a7464e7c51dd63b1a0034b4c3-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1424/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://74ec29e5bc845aa246fdb59f5502230e7a11abee-chi-pr.enterprise.ctl.io" target="_blank"> https://74ec29e5bc845aa246fdb59f5502230e7a11abee-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1434/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-h4lipi, https://ops.elasticbox.com/services/instances/i-umhhy5

**Pull request merged**
