### PR TITLE
[FSPE-6376] Added opacity utility

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-6376

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://e57fb245fd90d593545b4c01dae6c537c79349ce-chi-pr.enterprise.ctl.io" target="_blank"> https://e57fb245fd90d593545b4c01dae6c537c79349ce-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1399/ for more details.

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://e57fb245fd90d593545b4c01dae6c537c79349ce-chi-pr.enterprise.ctl.io" target="_blank"> https://e57fb245fd90d593545b4c01dae6c537c79349ce-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1401/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1421/ for more details.

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://6eb9eb29764e5e5bf0e67576664bb2e9e8a02a04-chi-pr.enterprise.ctl.io" target="_blank"> https://6eb9eb29764e5e5bf0e67576664bb2e9e8a02a04-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1422/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-e8txrl, https://ops.elasticbox.com/services/instances/i-bof672, https://ops.elasticbox.com/services/instances/i-59akcl

**Pull request merged**
