### PR TITLE
[PE-4368] Added backstop tests for Sidenav

### PR DESCRIPTION
**Pull request by janibolkvadze**
https://ctl.atlassian.net/browse/PE-4368

@jllr @mattnickles

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://313e6bc6fbcf93a928325d2967bd2ac390f25ab3-chi-pr.enterprise.ctl.io" target="_blank"> https://313e6bc6fbcf93a928325d2967bd2ac390f25ab3-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/665/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://3aa06b1b34b615d47f435a19f98cf223749ac575-chi-pr.enterprise.ctl.io" target="_blank"> https://3aa06b1b34b615d47f435a19f98cf223749ac575-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/669/ for more details.

**Comment by jllr** [comment]
@janibolkvadze I am missing sizes examples too. Please add them to the tests.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://6252fdc3b312d5a7538a0362dbebf0a1a86cef28-chi-pr.enterprise.ctl.io" target="_blank"> https://6252fdc3b312d5a7538a0362dbebf0a1a86cef28-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/687/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://43497c0ebb2c108b8d3de402dbd8e647e919399f-chi-pr.enterprise.ctl.io" target="_blank"> https://43497c0ebb2c108b8d3de402dbd8e647e919399f-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/688/ for more details.

**Comment by jllr** [comment]
@janibolkvadze I'm missing base examples of Sidenav. Please add them.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://cdf447a188471ce631822ab2657f8d2a090265c0-chi-pr.enterprise.ctl.io" target="_blank"> https://cdf447a188471ce631822ab2657f8d2a090265c0-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/690/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-xzpfwq, https://ops.elasticbox.com/services/instances/i-5us83u, https://ops.elasticbox.com/services/instances/i-rukfp6, https://ops.elasticbox.com/services/instances/i-s2sdyx, https://ops.elasticbox.com/services/instances/i-1t9m8y

**Pull request merged**
