### PR TITLE
[PE-4807] Fixed IE11 Progress web component value atrr

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://b57578b68357db123906a76a80883ba7d52d7680-chi-pr.enterprise.ctl.io" target="_blank"> https://b57578b68357db123906a76a80883ba7d52d7680-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/932/ for more details.

**Comment by janibolkvadze** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://b57578b68357db123906a76a80883ba7d52d7680-chi-pr.enterprise.ctl.io" target="_blank"> https://b57578b68357db123906a76a80883ba7d52d7680-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1508/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-qx046c

**Pull request closed without merging**
