### PR TITLE
[FSPE-5766] Added user settings icon

### PR DESCRIPTION
**Pull request by mattnickles**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://d0308d5f573bcead86f1a86b173cce9543e6315a-chi-pr.enterprise.ctl.io" target="_blank"> https://d0308d5f573bcead86f1a86b173cce9543e6315a-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1270/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://d0308d5f573bcead86f1a86b173cce9543e6315a-chi-pr.enterprise.ctl.io" target="_blank"> https://d0308d5f573bcead86f1a86b173cce9543e6315a-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1271/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-aaic81

**Pull request merged**
