### PR TITLE
[CHI-XXX] Prettier configuration for JavaScript/TypeScript files.

### PR DESCRIPTION
**Pull request by dani-cl-madrid**
Added Prettier config file for JavaScript and specially TypeScript files used in the Custom Elements version of Chi. Please @srinath-koneru, @SergioQCL review. This is the moment to propose any other desired rule. Once merged, rebase your PR and configure your code editors to use it. It should work with VSCode and WebStorm easily. I will ask @HectorGarciaAlvarez to add a test in the Jenkins to prevent non formatted files to be merged. TIA.

### CODE REVIEW

**Comment by srinath-koneru** [comment]
I would love if we can run a pre-commit to check whether files are well formatted before even it gets pushed, it should be good for the devs.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/90/ for more details.

**Comment by dani-cl-madrid** [comment]
> @dani-cl-madrid I would love if we can run a pre-commit to check whether files are well formatted before even it gets pushed, it should be good for the devs. Thoughts @SergioQCL.

This file is not going to make any changes by its own.
Just [download the file](https://raw.githubusercontent.com/CenturyLinkCloud/ux-chi/f4779f11937d867c7bf8d02f1ef90cd93a2f1bcc/.prettierrc), include it in the project root folder.
You'll also need a working version of the prettier command. Install it globally in your machine by: 
```
npm install -g prettier
```

Then, configure your code editor to work with prettier. To check a file, you have to open it and then, open the command palette of your editor and write prettier. In my case, I push Cmd+Opt+Shift+P to format the file automatically.

**Comment by SergioQCL** [comment]
I think we should get used to run prettier locally before submitting any file and PR so that's a good way of doing so. 

For VSCode, after installing prettier plugin, just press _cmd + shift + P_. Then, type _format document with.._ and select _Prettier_
After that, just pressing _shift + option + F_ will format all the document.

**Comment by dani-cl-madrid** [comment]
@jllr @mattnickles Please, merge. This is going to be useful to write consistent styled code in the stencil and JavaScript part. TIA

**Pull request merged**
