### PR TITLE
[PE-4023] Removed legacy css and added new tests

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/PE-4023

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://64d7b21d108dc1dc70a8bc04bf8adf518e8724e3-chi-pr.enterprise.ctl.io" target="_blank"> https://64d7b21d108dc1dc70a8bc04bf8adf518e8724e3-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/771/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://28623e6bfb222a04f3710052da7584255615327b-chi-pr.enterprise.ctl.io" target="_blank"> https://28623e6bfb222a04f3710052da7584255615327b-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/779/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://beb699206355ece5c8d111f146c6a1f00807d70c-chi-pr.enterprise.ctl.io" target="_blank"> https://beb699206355ece5c8d111f146c6a1f00807d70c-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/780/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://7173906e8127fb67b3d40248007c3bdbcf5b13b2-chi-pr.enterprise.ctl.io" target="_blank"> https://7173906e8127fb67b3d40248007c3bdbcf5b13b2-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/781/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://2f5ae78f6709aca5c07486b5a5c6870561c50d35-chi-pr.enterprise.ctl.io" target="_blank"> https://2f5ae78f6709aca5c07486b5a5c6870561c50d35-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/791/ for more details.

**Comment by jllr** [comment]
@mattnickles I have updated the branch and I can't find these references in the code. Where did you find those references?

**Comment by mattnickles** [comment]
@jllr on the avatar page

image

image

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://0b2407e2bfa899e3550fdea20208755c3613ba89-chi-pr.enterprise.ctl.io" target="_blank"> https://0b2407e2bfa899e3550fdea20208755c3613ba89-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/797/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://12b01fb4a67954e430d9d3e72124dc9ce2998e32-chi-pr.enterprise.ctl.io" target="_blank"> https://12b01fb4a67954e430d9d3e72124dc9ce2998e32-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/801/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-ne6ojz, https://ops.elasticbox.com/services/instances/i-qfkrqe, https://ops.elasticbox.com/services/instances/i-dp2rlo, https://ops.elasticbox.com/services/instances/i-8j8ca9, https://ops.elasticbox.com/services/instances/i-iousdr, https://ops.elasticbox.com/services/instances/i-hty1ey, https://ops.elasticbox.com/services/instances/i-kgro7j

**Pull request merged**
