### PR TITLE
[PE-4516] Fixed CE closing attribute inconsistency

### PR DESCRIPTION
**Pull request by janibolkvadze**
### Commit summary:

- [x] Changed `dismissible` attribute of Alert CE to more generalistic `closable`
- [x] Changed Drawer CE to closable by default, by adding attribute `non-closable` to render Drawer without close button
- [x] Changed alert `-dismiss` class to `-close`
- [x] Changed alert `m-alert__dismiss-button` to `m-alert__close-button`

@dani-cl-madrid @mattnickles @jllr 

https://ctl.atlassian.net/browse/PE-4516

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://d161091d300e2cada87f4ef39f1ffe47f0cd3db6-chi-pr.enterprise.ctl.io" target="_blank"> https://d161091d300e2cada87f4ef39f1ffe47f0cd3db6-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/761/ for more details.

**Comment by janibolkvadze** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://d161091d300e2cada87f4ef39f1ffe47f0cd3db6-chi-pr.enterprise.ctl.io" target="_blank"> https://d161091d300e2cada87f4ef39f1ffe47f0cd3db6-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/763/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://b9f0ce73b83eb9ccfeb0508420c362b70cd38cce-chi-pr.enterprise.ctl.io" target="_blank"> https://b9f0ce73b83eb9ccfeb0508420c362b70cd38cce-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/764/ for more details.

**Comment by jllr** [comment]
@janibolkvadze please solve conflicts

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://095bab669b637fb430f99a82d62a202c879dd4b5-chi-pr.enterprise.ctl.io" target="_blank"> https://095bab669b637fb430f99a82d62a202c879dd4b5-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/773/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://6612e999dd33c4d12c5b02bdb233615e43a28b6d-chi-pr.enterprise.ctl.io" target="_blank"> https://6612e999dd33c4d12c5b02bdb233615e43a28b6d-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/778/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-bak51m, https://ops.elasticbox.com/services/instances/i-ywm5zg, https://ops.elasticbox.com/services/instances/i-yj2tlj, https://ops.elasticbox.com/services/instances/i-gjfkxd

**Pull request merged**
