### PR TITLE
[PE-4792] Fixed chi-number-input accessibility errors

### PR DESCRIPTION
**Pull request by janibolkvadze**
https://ctl.atlassian.net/browse/PE-4792

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/924/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://8011b73c8c152af03b1fe191358f5201ef16d236-chi-pr.enterprise.ctl.io" target="_blank"> https://8011b73c8c152af03b1fe191358f5201ef16d236-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/925/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-oykrkn

**Pull request merged**
