### PR TITLE
[FSPE-6972] Improved striped behavior and added row child container for special cases in data table

### PR DESCRIPTION
**Pull request by jllr**
https://ctl.atlassian.net/browse/FSPE-6972

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://73d2b300381b2fa1ca377bd6633ec23498995eae-chi-pr.enterprise.ctl.io" target="_blank"> https://73d2b300381b2fa1ca377bd6633ec23498995eae-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1712/ for more details.

**Review by janibolkvadze — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1722/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://d969967a1b9e7a765913e2de09225b5a27006c83-chi-pr.enterprise.ctl.io" target="_blank"> https://d969967a1b9e7a765913e2de09225b5a27006c83-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1723/ for more details.

**Review by mattnickles — APPROVED** [review]
Looks good! One minor thing to address tomorrow - we'll need to exclude striped behavior from portal mobile view.

**Comment by jllr** [comment]
@mattnickles good catch!

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://ca304173a25d23daaf8a987fdceb0506aeb6cfdc-chi-pr.enterprise.ctl.io" target="_blank"> https://ca304173a25d23daaf8a987fdceb0506aeb6cfdc-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1726/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-irq9t4, https://ops.elasticbox.com/services/instances/i-ge784n, https://ops.elasticbox.com/services/instances/i-igo2q0

**Pull request merged**
