### PR TITLE
[CHI] Stencil updated to version 1.1.6

### PR DESCRIPTION
**Pull request by SergioQCL**
- Stencil updated to latest version (1.1.6)
- Stencil-sass updated to latest version (1.0.1)
- Fixes made in some components in order to compile with this new version (basically adding __h__ to imports and setting some methods to __async__)

@dani-cl-madrid, @srinath-koneru, @jllr please take a look

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/184/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/185/ for more details.

**Comment by srinath-koneru** [comment]
@SergioQCL All reflectToAttr should be changed to reflect and I see something going on with the drawer interaction example we might have to check that.

**Comment by SergioQCL** [comment]
@srinath-koneru I don't really know if that's the case. I saw this thread some time ago: https://github.com/ionic-team/stencil/issues/529 in which it seems they went for _reflecttoattr_ instead of _reflect_, but I don't know if they changed it again. Have you tried both cases?

Apart from that, what's happening with the drawer element?

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/194/ for more details.

**Comment by SergioQCL** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/195/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/199/ for more details.

**Comment by srinath-koneru** [comment]
Looks good.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/281/ for more details.

**Pull request closed without merging**
