### PR TITLE
[CHI-316] Footer component colums are not responsive

### PR DESCRIPTION
**Pull request by davidojedacl**
@mattnickles @jllr

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/198/ for more details.

**Comment by davidojedacl** [comment]
> Looks good. Can we fix this one as well? We just need to set the default flex direction to column and add a respond-to(sm) rule which sets it to row
> 
> image

**Comment by davidojedacl** [comment]
I saw on sm viewport problem like this. Maybe is better to add respond-to(md) 
Screen Shot 2019-07-22 at 12 18 25 PM

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/205/ for more details.

**Pull request merged**
