### PR TITLE
[PE-3848] Add new checkbox markup

### PR DESCRIPTION
**Pull request by jllr**
@janibolkvadze 

https://ctl.atlassian.net/browse/PE-3848

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/411/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/415/ for more details.

**Comment by mattnickles** [comment]
@jllr Buggy on Edge

Edge 15-18
image

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/420/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/433/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/435/ for more details.

**Pull request merged**
