### PR TITLE
[FSPE-6596] Prepared Chi 3.4.0 release

### PR DESCRIPTION
**Pull request by mattnickles**
https://ctl.atlassian.net/browse/FSPE-6596

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://545c172a1501095876e8905c9de176152739ba1e-chi-pr.enterprise.ctl.io" target="_blank"> https://545c172a1501095876e8905c9de176152739ba1e-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1599/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://83ee1c5493d276935dce0149b4c831d37a9b41bf-chi-pr.enterprise.ctl.io" target="_blank"> https://83ee1c5493d276935dce0149b4c831d37a9b41bf-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1600/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-lojlao, https://ops.elasticbox.com/services/instances/i-kkj6aq

**Pull request merged**
