### PR TITLE
Documentation-fixes-3.8.0

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://cc9466a495f3f56d666117bc3b6c1eafeab74bbc-chi-pr.enterprise.ctl.io" target="_blank"> https://cc9466a495f3f56d666117bc3b6c1eafeab74bbc-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1742/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://edb68a2828a5db6b83debfed37a6feea0b3d82ef-chi-pr.enterprise.ctl.io" target="_blank"> https://edb68a2828a5db6b83debfed37a6feea0b3d82ef-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1743/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-4ns1e4, https://ops.elasticbox.com/services/instances/i-iew322

**Pull request merged**
