### PR TITLE
[FIX] Fixed documentation defects for Chi 3.4.0

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://1bd5ca6390a7d041435e04ab6aa89050e0ea825e-chi-pr.enterprise.ctl.io" target="_blank"> https://1bd5ca6390a7d041435e04ab6aa89050e0ea825e-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1601/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://7a940b295dadd5301eda8fbe537947f1b67dc709-chi-pr.enterprise.ctl.io" target="_blank"> https://7a940b295dadd5301eda8fbe537947f1b67dc709-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1602/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-b3wc7w, https://ops.elasticbox.com/services/instances/i-6fkfon

**Pull request merged**
