### PR TITLE
1st CICD Jenkinsfile

### PR DESCRIPTION
**Pull request by jfranciscohernbal**
1st CICD Jenkinsfile for Unified Jenkins and other required files. Still subject to changes, tagged as draft, depending on the changes that may be requested tomorrow morning.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/1799/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://13412ec85d4db6068934d09fe42844b7831a6c56-chi-pr.enterprise.ctl.io" target="_blank"> https://13412ec85d4db6068934d09fe42844b7831a6c56-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1805/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://ceb4c7240196d6d900aac0b6c6b4eabef4e0fcb6-chi-pr.enterprise.ctl.io" target="_blank"> https://ceb4c7240196d6d900aac0b6c6b4eabef4e0fcb6-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1806/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://7892f4af497937a8d5a00630189f35d809f12f1d-chi-pr.enterprise.ctl.io" target="_blank"> https://7892f4af497937a8d5a00630189f35d809f12f1d-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1812/ for more details.

**Review by janibolkvadze — APPROVED** [review]

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://f002282a4d4a2bbc9a2510a96d1506092f10cf82-chi-pr.enterprise.ctl.io" target="_blank"> https://f002282a4d4a2bbc9a2510a96d1506092f10cf82-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1816/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1817/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-fwdj2e, https://ops.elasticbox.com/services/instances/i-5okmps, https://ops.elasticbox.com/services/instances/i-v9mxf7, https://ops.elasticbox.com/services/instances/i-qcb17m, https://ops.elasticbox.com/services/instances/i-tid6y6

**Pull request merged**
