### PR TITLE
Updated Chi asset URLs in Boilerplates

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1520/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Build was ABORTED. See http://jenkins.elasticbox.com/job/chi_pull_request/1521/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://818ef9c4a89ee79a0dc1e429496982f6ff07e664-chi-pr.enterprise.ctl.io" target="_blank"> https://818ef9c4a89ee79a0dc1e429496982f6ff07e664-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/1522/ for more details.

**Review by jllr — APPROVED** [review]

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-xeme6w

**Pull request merged**
