### PR TITLE
[PE-4730] Fix documentation bugs

### PR DESCRIPTION
**Pull request by mattnickles**
**Bug Fixes**
- Fixed bug in Alert component which caused alert icons to resize/squish on small viewports.
- Fixed bug in Alert component which rendered insufficient spacing between title and multi-line text.
- Fixed inconsistency in Breadcrumb component where sizes were not consistent with other Chi components.
- Fixed issue with documentation heading elements overlaying surrounding content. A pseudo before element was displayed on anchored headings. This is what was overlaying surrounding links, etc. and preventing them from being clicked.
- Fixed bug in Date picker component which caused non-active days to render with a semi-bold font-weight instead of normal.
- Fixed bug in File Input component where button left and right padding were inconsistent with Button component padding.
- Fixed broken documentation examples.
- Fixed broken documentation links.
- Removed mentions of "atom" and "molecule" prefixes from the naming convention guidance section in Development Workflow.

**Improvements**
- Added CSS support for a `-disabled` class to Tab component.
- Added "Web Component" and "HTML Blueprint" tabs to every example in every component. This will provide consistency across component pages and help illustrate when a Web Component is not yet available.
- Added focus state to documentation anchor links.
- Added focus state to documentation header logo.
- Added focus state to documentation sidenav tab links.
- Replaced documentation container elements with more semantic html5 tags (main, nav, header, article).
- Renamed documentation sidenav from aside.pug to sidenav.pug.
- Renamed documentation heading.pug to titlebar.pug.
- Updated introduction "Composable" text.
- Improved markup for illustration hero unit.
- Removed SVG icon examples from Avatar documentation.
- Replaced SVG icon examples in Tab documentation with web font.
- Improved documentation example for Header Tab Navigation with both a light and dark version. Also made data in the example more generic.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://821801f339afbe2e52d2d82b737cc8ee6653d75f-chi-pr.enterprise.ctl.io" target="_blank"> https://821801f339afbe2e52d2d82b737cc8ee6653d75f-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/882/ for more details.

**Comment by jllr** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://821801f339afbe2e52d2d82b737cc8ee6653d75f-chi-pr.enterprise.ctl.io" target="_blank"> https://821801f339afbe2e52d2d82b737cc8ee6653d75f-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/883/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-aaf5t3

**Pull request merged**
