### PR TITLE
[PE-4084] Fixed icon click of datepicker CE and JS

### PR DESCRIPTION
**Pull request by janibolkvadze**
Fixed the issue of clicking on the calendar icon in IE

@mattnickles @jllr 

https://ctl.atlassian.net/browse/PE-4084

--- Please don't merge yet ---

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/501/ for more details.

**Comment by janibolkvadze** [comment]
Regarding placeholder behavior in IE11: Looks like disappearing placeholder is the default behavior in IE for all the form inputs. We tested Text inputs, textareas, etc and Focus hides placeholders.
From the :-ms-input-placeholder pseudo-class documentation from the Internet Explorer Developer Center:

> The placeholder text is displayed with the specified style until the field has focus, meaning that the field can be typed into. When the field has focus, it returns to the normal style of the input field and the placeholder text disappears.

The workaround would be to introduce a polyfill, but the ones I came across are heavy, not sure if it's worth it.
@mattnickles @jllr

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/506/ for more details.

**Comment by mattnickles** [comment]
@janibolkvadze Ah that's right. I agree, not worth it to change native behavior. Thanks for looking into it!

**Pull request merged**
