### PR TITLE
Fixed class of current Chi version in dropdown

### PR DESCRIPTION
**Pull request by janibolkvadze**

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/644/ for more details.

**Comment by DiegoSanjuan** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/646/ for more details.

**Comment by DiegoSanjuan** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://a0846aa98458c5306a7f8015abfdfc6fc598fac9-chi-pr.enterprise.ctl.io" target="_blank"> https://a0846aa98458c5306a7f8015abfdfc6fc598fac9-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/647/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-nsyuwy

**Pull request merged**
