### PR TITLE
[PE-4773] Popover improvements

### PR DESCRIPTION
**Pull request by mattnickles**
- Added support for a footer to Popover web component and html blueprint (needed to house buttons, links, etc.)
- Designed new way to visualize Popover positioning values in Positioning example.
- Replaced Popover custom content example with a more common use case.
- Improved text and usability in all other Popover examples.
- Improved Events layout in Popover properties tab.

### CODE REVIEW

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/chi_pull_request/896/ for more details.

**Comment by mattnickles** [comment]
test this please

**Comment by allyourbotsarebelongtous** [comment]
Your CHI Pull Request website is available for review at <a href="https://0655b574fb38086ff9b713a2a77940102be2765d-chi-pr.enterprise.ctl.io" target="_blank"> https://0655b574fb38086ff9b713a2a77940102be2765d-chi-pr.enterprise.ctl.io </a>

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/chi_pull_request/898/ for more details.

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://ops.elasticbox.com/services/instances/i-q1x1n4

**Pull request merged**
